/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as QuicksplitRouteRouteImport } from './routes/quicksplit/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as QuicksplitDashboardRouteImport } from './routes/quicksplit/dashboard'
import { Route as QuicksplitCreateSharedWalletRouteImport } from './routes/quicksplit/create-shared-wallet'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as PublicLoginRouteImport } from './routes/_public.login'
import { Route as QuicksplitWalletsWalletIdRouteImport } from './routes/quicksplit/wallets/$walletId'
import { Route as AppWalletsCreateRouteImport } from './routes/app/wallets/create'
import { Route as AppExerciseEditorRouteImport } from './routes/app/exercise.editor'

const AppExercisesLazyRouteImport = createFileRoute('/app/exercises')()

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const QuicksplitRouteRoute = QuicksplitRouteRouteImport.update({
  id: '/quicksplit',
  path: '/quicksplit',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AppExercisesLazyRoute = AppExercisesLazyRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AppRouteRoute,
} as any).lazy(() => import('./routes/app/exercises.lazy').then((d) => d.Route))
const QuicksplitDashboardRoute = QuicksplitDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => QuicksplitRouteRoute,
} as any)
const QuicksplitCreateSharedWalletRoute =
  QuicksplitCreateSharedWalletRouteImport.update({
    id: '/create-shared-wallet',
    path: '/create-shared-wallet',
    getParentRoute: () => QuicksplitRouteRoute,
  } as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const QuicksplitWalletsWalletIdRoute =
  QuicksplitWalletsWalletIdRouteImport.update({
    id: '/wallets/$walletId',
    path: '/wallets/$walletId',
    getParentRoute: () => QuicksplitRouteRoute,
  } as any)
const AppWalletsCreateRoute = AppWalletsCreateRouteImport.update({
  id: '/wallets/create',
  path: '/wallets/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExerciseEditorRoute = AppExerciseEditorRouteImport.update({
  id: '/exercise/editor',
  path: '/exercise/editor',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteRouteWithChildren
  '/quicksplit': typeof QuicksplitRouteRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/quicksplit/create-shared-wallet': typeof QuicksplitCreateSharedWalletRoute
  '/quicksplit/dashboard': typeof QuicksplitDashboardRoute
  '/app/exercises': typeof AppExercisesLazyRoute
  '/': typeof PublicIndexRoute
  '/app/exercise/editor': typeof AppExerciseEditorRoute
  '/app/wallets/create': typeof AppWalletsCreateRoute
  '/quicksplit/wallets/$walletId': typeof QuicksplitWalletsWalletIdRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppRouteRouteWithChildren
  '/quicksplit': typeof QuicksplitRouteRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/quicksplit/create-shared-wallet': typeof QuicksplitCreateSharedWalletRoute
  '/quicksplit/dashboard': typeof QuicksplitDashboardRoute
  '/app/exercises': typeof AppExercisesLazyRoute
  '/': typeof PublicIndexRoute
  '/app/exercise/editor': typeof AppExerciseEditorRoute
  '/app/wallets/create': typeof AppWalletsCreateRoute
  '/quicksplit/wallets/$walletId': typeof QuicksplitWalletsWalletIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteRouteWithChildren
  '/quicksplit': typeof QuicksplitRouteRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/quicksplit/create-shared-wallet': typeof QuicksplitCreateSharedWalletRoute
  '/quicksplit/dashboard': typeof QuicksplitDashboardRoute
  '/app/exercises': typeof AppExercisesLazyRoute
  '/_public/': typeof PublicIndexRoute
  '/app/exercise/editor': typeof AppExerciseEditorRoute
  '/app/wallets/create': typeof AppWalletsCreateRoute
  '/quicksplit/wallets/$walletId': typeof QuicksplitWalletsWalletIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/quicksplit'
    | '/login'
    | '/app/dashboard'
    | '/quicksplit/create-shared-wallet'
    | '/quicksplit/dashboard'
    | '/app/exercises'
    | '/'
    | '/app/exercise/editor'
    | '/app/wallets/create'
    | '/quicksplit/wallets/$walletId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/quicksplit'
    | '/login'
    | '/app/dashboard'
    | '/quicksplit/create-shared-wallet'
    | '/quicksplit/dashboard'
    | '/app/exercises'
    | '/'
    | '/app/exercise/editor'
    | '/app/wallets/create'
    | '/quicksplit/wallets/$walletId'
  id:
    | '__root__'
    | '/app'
    | '/quicksplit'
    | '/_public'
    | '/_public/login'
    | '/app/dashboard'
    | '/quicksplit/create-shared-wallet'
    | '/quicksplit/dashboard'
    | '/app/exercises'
    | '/_public/'
    | '/app/exercise/editor'
    | '/app/wallets/create'
    | '/quicksplit/wallets/$walletId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  QuicksplitRouteRoute: typeof QuicksplitRouteRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quicksplit': {
      id: '/quicksplit'
      path: '/quicksplit'
      fullPath: '/quicksplit'
      preLoaderRoute: typeof QuicksplitRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/app/exercises': {
      id: '/app/exercises'
      path: '/exercises'
      fullPath: '/app/exercises'
      preLoaderRoute: typeof AppExercisesLazyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/quicksplit/dashboard': {
      id: '/quicksplit/dashboard'
      path: '/dashboard'
      fullPath: '/quicksplit/dashboard'
      preLoaderRoute: typeof QuicksplitDashboardRouteImport
      parentRoute: typeof QuicksplitRouteRoute
    }
    '/quicksplit/create-shared-wallet': {
      id: '/quicksplit/create-shared-wallet'
      path: '/create-shared-wallet'
      fullPath: '/quicksplit/create-shared-wallet'
      preLoaderRoute: typeof QuicksplitCreateSharedWalletRouteImport
      parentRoute: typeof QuicksplitRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/quicksplit/wallets/$walletId': {
      id: '/quicksplit/wallets/$walletId'
      path: '/wallets/$walletId'
      fullPath: '/quicksplit/wallets/$walletId'
      preLoaderRoute: typeof QuicksplitWalletsWalletIdRouteImport
      parentRoute: typeof QuicksplitRouteRoute
    }
    '/app/wallets/create': {
      id: '/app/wallets/create'
      path: '/wallets/create'
      fullPath: '/app/wallets/create'
      preLoaderRoute: typeof AppWalletsCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/exercise/editor': {
      id: '/app/exercise/editor'
      path: '/exercise/editor'
      fullPath: '/app/exercise/editor'
      preLoaderRoute: typeof AppExerciseEditorRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppExercisesLazyRoute: typeof AppExercisesLazyRoute
  AppExerciseEditorRoute: typeof AppExerciseEditorRoute
  AppWalletsCreateRoute: typeof AppWalletsCreateRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppExercisesLazyRoute: AppExercisesLazyRoute,
  AppExerciseEditorRoute: AppExerciseEditorRoute,
  AppWalletsCreateRoute: AppWalletsCreateRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface QuicksplitRouteRouteChildren {
  QuicksplitCreateSharedWalletRoute: typeof QuicksplitCreateSharedWalletRoute
  QuicksplitDashboardRoute: typeof QuicksplitDashboardRoute
  QuicksplitWalletsWalletIdRoute: typeof QuicksplitWalletsWalletIdRoute
}

const QuicksplitRouteRouteChildren: QuicksplitRouteRouteChildren = {
  QuicksplitCreateSharedWalletRoute: QuicksplitCreateSharedWalletRoute,
  QuicksplitDashboardRoute: QuicksplitDashboardRoute,
  QuicksplitWalletsWalletIdRoute: QuicksplitWalletsWalletIdRoute,
}

const QuicksplitRouteRouteWithChildren = QuicksplitRouteRoute._addFileChildren(
  QuicksplitRouteRouteChildren,
)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  QuicksplitRouteRoute: QuicksplitRouteRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
