/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as PublicLoginRouteImport } from './routes/_public.login'
import { Route as AppWalletsCreateRouteImport } from './routes/app/wallets/create'

const AppExercisesLazyRouteImport = createFileRoute('/app/exercises')()

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AppExercisesLazyRoute = AppExercisesLazyRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AppRouteRoute,
} as any).lazy(() => import('./routes/app/exercises.lazy').then((d) => d.Route))
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AppWalletsCreateRoute = AppWalletsCreateRouteImport.update({
  id: '/wallets/create',
  path: '/wallets/create',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/exercises': typeof AppExercisesLazyRoute
  '/': typeof PublicIndexRoute
  '/app/wallets/create': typeof AppWalletsCreateRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/exercises': typeof AppExercisesLazyRoute
  '/': typeof PublicIndexRoute
  '/app/wallets/create': typeof AppWalletsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/exercises': typeof AppExercisesLazyRoute
  '/_public/': typeof PublicIndexRoute
  '/app/wallets/create': typeof AppWalletsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/login'
    | '/app/dashboard'
    | '/app/exercises'
    | '/'
    | '/app/wallets/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/login'
    | '/app/dashboard'
    | '/app/exercises'
    | '/'
    | '/app/wallets/create'
  id:
    | '__root__'
    | '/app'
    | '/_public'
    | '/_public/login'
    | '/app/dashboard'
    | '/app/exercises'
    | '/_public/'
    | '/app/wallets/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/app/exercises': {
      id: '/app/exercises'
      path: '/exercises'
      fullPath: '/app/exercises'
      preLoaderRoute: typeof AppExercisesLazyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/app/wallets/create': {
      id: '/app/wallets/create'
      path: '/wallets/create'
      fullPath: '/app/wallets/create'
      preLoaderRoute: typeof AppWalletsCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppExercisesLazyRoute: typeof AppExercisesLazyRoute
  AppWalletsCreateRoute: typeof AppWalletsCreateRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppExercisesLazyRoute: AppExercisesLazyRoute,
  AppWalletsCreateRoute: AppWalletsCreateRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
